In [11]:
# Importing the Required Libraries
import math
import numpy as np

In [12]:
# Setting the Values of theta for each of the Revolute Joints (1 per DoF: 7 total)
theta1 = 0
theta2 = 0
theta3 = 0
theta4 = 0
theta5 = 0
theta6 = 0
theta7 = 0

# This is the Home Position of the Robot Chosen
# Other Configurations can be chosen by Adjusting these Parameters

In [13]:
# Loading the DH Parameter Table for the 'Franka Emika Panda' Robot as a NumPy Array
# Each Row Represents [a(i-1) alpha(i-1) d(i) theta(i)] for each of the Joints
# Last Row are the DH Parameters for the End Effector from the last Joint
dh_table = np.array([[0,       0,            0.333, theta1], # Joint 1
                     [0,       -(math.pi)/2, 0,     theta2], # Joint 2
                     [0,       (math.pi)/2,  0.316, theta3], # Joint 3
                     [0.0825,  (math.pi)/2,  0,     theta4], # Joint 4
                     [-0.0825, -(math.pi)/2, 0.384, theta5], # Joint 5
                     [0,       (math.pi)/2,  0,     theta6], # Joint 6
                     [0.088,   (math.pi)/2,  0,     theta7], # Joint 7
                     [0,       0,            0, 0]])      # End Effector

In [14]:
# Simple Function for Sin Theta
def sin(theta):
  return math.sin(theta)

# Simple Function for Cos Theta
def cos(theta):
  return math.cos(theta)

# Function to Calculate the Transformation Matrix between Joint i-1 & i
def link_transformation_matrix(dh_parameters):
  a     = dh_parameters[0]
  alpha = dh_parameters[1]
  d     = dh_parameters[2]
  theta = dh_parameters[3]
  matrix = np.array([[cos(theta),            -sin(theta),           0,           a],
                     [sin(theta)*cos(alpha), cos(theta)*cos(alpha), -sin(alpha), -sin(alpha)*d],
                     [sin(theta)*sin(alpha), cos(theta)*sin(alpha), cos(alpha),  cos(alpha)*d],
                     [0,                     0,                     0,           1]])
  print("Intermediate Transformation Matrix:\n{}".format(matrix))
  return matrix

# Function to get the Total Transformation Matrix for the System
def transformation_matrix(dh_parameter_table):
  matrix = np.eye(4)
  for i in reversed(range(dh_parameter_table.shape[0])):
    matrix = np.dot(link_transformation_matrix(dh_parameter_table[i]),matrix)
  print("Final/Overall Transformation Matrix:\n{}".format(matrix))
  return matrix

# Calcuating the Position of a Point based in the Last Frame (8) wrt to the Ground Frame (0)
def calculate_ground_coordinates(x,y,z,transformation_matrix):
  ground_coords = np.dot(transformation_matrix,np.array([[x],[y],[z],[1.0]]))
  return (ground_coords[0,0], ground_coords[1,0], ground_coords[2][0])


In [15]:
# Case1 : Using all the 7 Frames
# Loading the DH Parameter Table for the 'Franka Emika Panda' Robot as a NumPy Array
# Each Row Represents [a(i-1) alpha(i-1) d(i) theta(i)] for each of the Joints
# Last Row are the DH Parameters for the End Effector from the last Joint
dh_table = np.array([[0,       0,            0.333, theta1], # Joint 1
                     [0,       -(math.pi)/2, 0,     theta2], # Joint 2
                     [0,       (math.pi)/2,  0.316, theta3], # Joint 3
                     [0.0825,  (math.pi)/2,  0,     theta4], # Joint 4
                     [-0.0825, -(math.pi)/2, 0.384, theta5], # Joint 5
                     [0,       (math.pi)/2,  0,     theta6], # Joint 6
                     [0.088,   (math.pi)/2,  0,     theta7], # Joint 7
                     [0,       0,            0, 0]])      # End Effector (Origin of the last frame)

In [16]:
# Calculating the Transformation Matrix for the Robotic System
system_transformation_matrix = transformation_matrix(dh_table)

Intermediate Transformation Matrix:
[[ 1. -0.  0.  0.]
 [ 0.  1. -0. -0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
Intermediate Transformation Matrix:
[[ 1.000000e+00 -0.000000e+00  0.000000e+00  8.800000e-02]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00 -0.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
Intermediate Transformation Matrix:
[[ 1.000000e+00 -0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00 -0.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
Intermediate Transformation Matrix:
[[ 1.00000000e+00 -0.00000000e+00  0.00000000e+00 -8.25000000e-02]
 [ 0.00000000e+00  6.12323400e-17  1.00000000e+00  3.84000000e-01]
 [-0.00000000e+00 -1.00000000e+00  6.12323400e-17  2.35132185e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Intermediate Transformation Matrix:


In [17]:
# Verifying the Position of the Origin of the End Effector
print("Position of Origin i.e. (0,0,0) of End Effector's Frame in Ground Coordinates: {}".format(calculate_ground_coordinates(0,0,0,system_transformation_matrix)))

Position of Origin i.e. (0,0,0) of End Effector's Frame in Ground Coordinates: (0.088, 6.162975822039155e-33, 1.033)


In [18]:
# Case2 : Using only the first 2 frames
# Loading the DH Parameter Table for the 'Franka Emika Panda' Robot as a NumPy Array
# Each Row Represents [a(i-1) alpha(i-1) d(i) theta(i)] for each of the Joints
# Last Row are the DH Parameters for the End Effector from the last Joint
dh_table = np.array([[0,       0,            0.333, theta1], # Joint 1
                     [0,       -(math.pi)/2, 0,     theta2], # Joint 2
                     [0,       0,            0, 0]])      # End Effector (Origin of the last frame)

In [19]:
# Calculating the Transformation Matrix for the Robotic System
system_transformation_matrix = transformation_matrix(dh_table)

Intermediate Transformation Matrix:
[[ 1. -0.  0.  0.]
 [ 0.  1. -0. -0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
Intermediate Transformation Matrix:
[[ 1.000000e+00 -0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17  1.000000e+00  0.000000e+00]
 [-0.000000e+00 -1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
Intermediate Transformation Matrix:
[[ 1.    -0.     0.     0.   ]
 [ 0.     1.    -0.    -0.   ]
 [ 0.     0.     1.     0.333]
 [ 0.     0.     0.     1.   ]]
Final/Overall Transformation Matrix:
[[ 1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17  1.000000e+00  0.000000e+00]
 [ 0.000000e+00 -1.000000e+00  6.123234e-17  3.330000e-01]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]


In [20]:
# Verifying the Position of the Origin of the End Effector
print("Position of Origin i.e. (0,0,0) of End Effector's Frame in Ground Coordinates: {}".format(calculate_ground_coordinates(0,0,0,system_transformation_matrix)))

Position of Origin i.e. (0,0,0) of End Effector's Frame in Ground Coordinates: (0.0, 0.0, 0.333)
